---
name: Cobalt
description: A powerful anticheat made to destroy hackers from your server for PocketMine-MP.
authors: [ReinfyTeam, xqwtxon, xwertxy, UnknownNull, ClydeNoIQ]
version: 1.3.1 
website: "https://github.com/ClydeNoIQ/Cobalt/"
src-namespace-prefix: Blitz\Cobalt
main: Blitz\Cobalt\CobaltAC
api: 5.0.0
permissions:
     cobalt.command:
          default: op
          description: Cobalt main command.
...
